#!/usr/bin/env bash

# Compile the C++ files
g++ -o generator generator.cpp
# g++ -o generator treeGen.cpp
g++ -o correctSolution correctSolution.cpp
g++ -o F F.cpp

# Make sure the stress testing script is executable
chmod +x stressTesting.sh

# Use user input or fallback to default (20)
numTests=${1:-20}

# Run the stress test
./stressTesting.sh F correctSolution generator $numTests
