#!/usr/bin/env bash

# Compile the C++ files
g++ -o generator generator.cpp
# g++ -o generator treeGen.cpp

g++ -o correctSolution correctSolution.cpp
# g++ -o multiSolutionChecker multiSolutionChecker.cpp

g++ -o mySolution mySolution.cpp

# Make sure the stress testing script is executable
chmod +x stressTesting.sh
chmod +x stressTestingMultiSolution.sh


# Run the stress test
./stressTesting.sh mySolution correctSolution generator 
# ./stressTestingMultiSolution.sh mySolution multiSolutionChecker generator 
